 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/message_groups", type: :request do
  # MessageGroup. As you add validations to MessageGroup, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MessageGroup.create! valid_attributes
      get message_groups_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      message_group = MessageGroup.create! valid_attributes
      get message_group_url(message_group)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_message_group_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      message_group = MessageGroup.create! valid_attributes
      get edit_message_group_url(message_group)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MessageGroup" do
        expect {
          post message_groups_url, params: { message_group: valid_attributes }
        }.to change(MessageGroup, :count).by(1)
      end

      it "redirects to the created message_group" do
        post message_groups_url, params: { message_group: valid_attributes }
        expect(response).to redirect_to(message_group_url(MessageGroup.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MessageGroup" do
        expect {
          post message_groups_url, params: { message_group: invalid_attributes }
        }.to change(MessageGroup, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post message_groups_url, params: { message_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested message_group" do
        message_group = MessageGroup.create! valid_attributes
        patch message_group_url(message_group), params: { message_group: new_attributes }
        message_group.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the message_group" do
        message_group = MessageGroup.create! valid_attributes
        patch message_group_url(message_group), params: { message_group: new_attributes }
        message_group.reload
        expect(response).to redirect_to(message_group_url(message_group))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        message_group = MessageGroup.create! valid_attributes
        patch message_group_url(message_group), params: { message_group: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested message_group" do
      message_group = MessageGroup.create! valid_attributes
      expect {
        delete message_group_url(message_group)
      }.to change(MessageGroup, :count).by(-1)
    end

    it "redirects to the message_groups list" do
      message_group = MessageGroup.create! valid_attributes
      delete message_group_url(message_group)
      expect(response).to redirect_to(message_groups_url)
    end
  end
end
